---
version: '2.1'

networks:
  frontend:
    external: true

services:

  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - /mnt/backups/second_backup:/backups
      - /:/source
    networks:
      - frontend
    restart: unless-stopped