version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: artifactory
    ports:
     - 8581:8081
    volumes:
     - arti-data:/var/opt/jfrog/artifactory
     - /mnt/data/workspace/boilerplates/docker-compose/artifactory/artifactory/var/etc:/var/etc
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  arti-data:
    driver: local
