version: '3'
services:
  artifactory:
    image: sonatype/nexus3
    container_name: nexus
    ports:
     - 8081:8081
    volumes:
     - nexus-data:/nexus-data
    restart: always

volumes:
  nexus-data:
    external: true
    name: nexus-data
