version: '3.5'
services:
  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
