version: "3.9"

# Connect to the existing traefik network
networks:
  frontend:
    external: true

services:
  netdata:
    image: netdata/netdata:v1.32
    container_name: netdata
    hostname: cergy-server
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro 
      - /etc/os-release:/host/etc/os-release:ro
    command: -u valentin
    networks:
      - frontend
    env_file:
      - .env

volumes:
  netdataconfig:
  netdatalib:
  netdatacache: