version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVEURURL=vpn.pival.fr #optional
      - SERVERPORT=51820 #optional
      - PEERS=VAL_PC, VAL_MAC, PILA_PC, VAL_PHONE, PILA_PHONE, MANUEL_PHONE, LAURENCE_PHONE, CAPSULE #optional
      #- PEERDNS=192.168.1.93 #optional
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.10.10.0 #optional
      - ALLOWEDIPS=192.168.1.0/24, 10.10.10.0/32, 10.10.10.9/32, 10.10.10.10/32, 0.0.0.0/0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1