
version: '3'

networks:
  backend:
    external: true

volumes:
  uptimekuma-data:
    driver: local

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    networks:
      - backend
    ports:
      - 3001:3001
    volumes:
      - uptimekuma-data:/app/data
    restart: unless-stopped