
version: '3'

volumes:
  uptimekuma-data:
    driver: local

# Connect to the existing traefik network
networks:
  frontend:
    external: true
  backend:
    external: true

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    networks:
      - frontend
      - backend # Connect with the homeassistant fallback controler webhook
    volumes:
      - uptimekuma-data:/app/data
    restart: unless-stopped