version: "2"

# Connect to the existing traefik network
networks:
  traefik_default:
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - /apps/vaultwarden/bw-data:/data
      - /etc/localtime:/etc/localtime
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
      TZ: 'Europe/Paris'
      ADMIN_TOKEN: 'token'
    ports:
      - 3012:3012
      - 7080:80 # Facultatif avec Traefikudisksd[912]: udisks_mount_get_mount_path: assertion 'mount->type == UDISKS_MOUNT_TYPE_FILESYSTEM' failed