version: "2.1"
services:
  samba-share:
    image: elswork/samba
    container_name: samba-share
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./share:/share/folder
      #- ./smb.conf:/etc/samba/smb.conf:ro #config
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
    command: -u "1000:1000:valentin:valentin:margera" -s "CergySambaShare:/share/folder:rw:valentin"