version: "3"

networks:
  backend:
    external: true

volumes:
  webhook-lib:

services:
#  homeassistant:
#    image: ghcr.io/home-assistant/home-assistant:stable
#    container_name: homeassistant
#    restart: unless-stopped
#    privileged: true
#    network_mode: host
#    volumes:
#      - ./HomeAssistantConfig:/config
#      - /etc/localtime:/etc/localtime:ro

  homeassistant-webhook:
    image: ncarlier/webhookd
    container_name: homeassistant-webhook
    restart: unless-stopped
    networks:
      - backend
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./webhook:/var/opt/webhookd/scripts
      - webhook-lib:/var/lib/docker
    command: "webhookd --scripts=/var/opt/webhookd/scripts"