version: "3"

networks:
  frontend:
    external: true
  backend:
    external: true

services:
#  homeassistant:
#    image: ghcr.io/home-assistant/home-assistant:stable
#    container_name: homeassistant
#    restart: unless-stopped
#    privileged: true
#    network_mode: host
#    volumes:
#      - ./HomeAssistantConfig:/config
#      - /etc/localtime:/etc/localtime:ro

  homeassistant-webhook:
    image: ncarlier/webhookd
    container_name: homeassistant-webhook
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./webhook:/var/opt/webhookd/scripts
    ports:
      - "8888:8080"
    command: "webhookd --scripts=/var/opt/webhookd/scripts"